# This is the main configuration file for the plugin.
# You can find more information about this file here:
# https://github.com/josantonius/minecraft-purge

# Purge sound announce.
# This is the sound that will be played when the purge announces.
# Default: minecraft:purge.sound.announce
announcePurgeSound: "minecraft:purge.sound.announce"

# Purge sound.
# This is the sound that will be played when the purge ongoing.
# Default: minecraft:purge.sound.ongoing
ongoingPurgeSound: "minecraft:purge.sound.ongoing"

# Purge sound end.
# This is the sound that will be played when the purge ends.
# Default: minecraft:purge.sound.end
endPurgeSound: "minecraft:purge.sound.end"

# Commands that players without immunity will not be allowed to use during the purge.
blockedCommands: null

# Main world. Here players will be sent from the locked worlds.
mainWorld: null

# Worlds that will not be used during the purge.
blockedWorlds: null

# Apply a cooldown of n seconds between uses to the ender pearls.
enderPearlCooldown: null

# Apply a cooldown of n seconds between uses to the firework rockets.
fireworkRocketCooldown: null